OpenTermsArchive/pga-declarations

declarations/Twitter.filters.js, declarations/Twitter.json
=> Add Twitter declaration

declarations/Facebook.filters.js, declarations/Facebook.json, package.json
I added the facebook declaration but could not test/lint so I updated the package.json from contrib-declarations. This still seems to not pass schema test.
=> Add Facebook declaration

declarations/Twitter.history.json, declarations/Twitter.json
Updated pull request with history file
Issues #23 #22
=> Update Twitter tos & pp

declarations/Facebook.filters.js, declarations/Facebook.history.json, declarations/Facebook.json
Fix blinking from issues #24 #32
=> Fix Facebook TOS & PP

declarations/Facebook.filters.js, declarations/Facebook.history.json, declarations/Facebook.json
Created a filter to remove links from the document. The changing links were causing blinking on these declarations.
=> Fix Facebook blinking 

declarations/Instagram.filters.js, declarations/Instagram.history.json, declarations/Instagram.json
Used same filters from #45 to fix the blinking of these declarations
=> Fix Instagram blinking

declarations/Instagram.filters.js, declarations/Instagram.history.json, declarations/Instagram.json
Created a filter to remove images that were causing blinking
=> Remove img from blinking Instagram service declarations

declarations/Facebook.json
Start tracking community guidelines, based off of france-elections declarations
=> Add Facebook community guidelines declarations

declarations/Tumblr.json
This webpage seems to be blocked when run through contrib tool and locally. I know this is the right selector but it kicks back an InaccessibleContentError everytime I test it
=> Add Community Guidelines - Tumblr

declarations/Instagram.filters.js, declarations/Instagram.history.json, declarations/Instagram.json
I added new filters to remove all the Query Params in the blinking ToS.
=> Add new removeQueryParm filters to ToS

.github/workflows/test.yml, deployment/requirements.yml, package-lock.json, package.json
- Update deployment to start the collection metadata API; the API will be exposed at http://134.102.58.70/api/v1/docs
- Add linting to test script
- Add a lint step in CI 
- Update patches of dependencies
=> Deploy collection metadata API

declarations/TikTok.json
Combining multiple guidelines into one document
=> Fix TikTok Community Guidelines (#147)

declarations/Twitter.json
Updated links for Twitter (X) community guidelines
=> Fix Twitter Community Guidelines (#168)

declarations/LinkedIn.json
=> Fix LinkedIn - Terms of Service #171

declarations/Quora.json
=> Update Quora CG

.github/workflows/test.yml
After receiving valuable feedback from an [external contributor](https://github.com/OpenTermsArchive/demo-declarations/pull/30), we've [updated our Demo reference repository](https://github.com/OpenTermsArchive/demo-declarations/pull/31) to enable automatic test triggers for PRs originating from forks. We encourage you to incorporate these improvements into your own repository by reviewing and merging this PR.
=> Ensure test workflow is triggered on updates to pull requests originating from forks

package-lock.json, package.json
Fixed in engine [v2.3.1](https://github.com/OpenTermsArchive/engine/blob/main/CHANGELOG.md#231---2024-10-22) and [v2.3.2](https://github.com/OpenTermsArchive/engine/blob/main/CHANGELOG.md#232---2024-10-23)
=> Update engine to avoid inconsistent states and duplicates on GitHub issues reports

declarations/Spotify.json
=> Fix Spotify Community Guidelines (#404)

declarations/Twitch.json
Fixing the selector and adding a remove
=> Fix Twitch_ToS

declarations/Twitch.json
Fixing the selector, adding a remove and the filter
=> Fix Twitch TP

declarations/Spotify.json
=> Fix Spotify CG

declarations/Facebook.json
=> Fix Facebook PP
